services:
  postgres:
    profiles: ["db", "infra", "all"]
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guardrails
    volumes:
       - guardrails_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  jaeger:
    profiles: ["otel", "infra", "all"]
    image: jaegertracing/jaeger:latest
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

  guardrails-server:
    network_mode: host
    profiles: ["server", "all"]
    image: guardrails-server:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  guardrails_postgres_data: