# FROM python:3.6
FROM public.ecr.aws/docker/library/python:3-slim

# Create app directory
WORKDIR /app

# start the virtual environment
RUN python3 -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./guardrails-sdk ./guardrails-sdk

# Copy the requirements file
COPY requirements.txt .

RUN pip install ./guardrails-sdk

# Install app dependencies
RUN pip install -r requirements.txt

# Freeze dependencies
RUN pip freeze > requirements.txt

# Copy the whole folder inside the Image filesystem
COPY . .

EXPOSE 8000

CMD gunicorn --bind 0.0.0.0:8000 --timeout=5 --threads=10 --reload wsgi:app
