version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-changeme}
      POSTGRES_DATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGUSER:-postgres}@guardrails.com"
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD:-changeme}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  guardrails-api:
    image: guardrails-api:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: "8000"
    ports:
      - "8000:8000"
    environment: 
      PGPORT: 5432
      REDIS_ENDPOINT: http://postgres:5432
      PGDATABASE: postgres
      PGHOST: postgres
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-changeme}
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
    depends_on:
      - postgres