FROM public.ecr.aws/docker/library/python:3.11.6-slim

# Create app directory
WORKDIR /app

# check the version
RUN python3 --version
# start the virtual environment
RUN python3 -m venv /opt/venv

# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

# Install gcc
RUN apt-get update
RUN apt-get install -y gcc

COPY ./guardrails-sdk ./guardrails-sdk

COPY ./guard-rails-api-client ./guard-rails-api-client

COPY ./guardrails-custom-validators ./guardrails-custom-validators

# Copy the requirements file
COPY requirements.txt .

RUN pip install ./guardrails-sdk
RUN pip install ./guard-rails-api-client

# Install app dependencies
RUN pip install -r requirements-lock.txt

# Download punkt data
RUN python -m nltk.downloader -d /opt/nltk_data punkt

# Freeze dependencies
RUN pip freeze > requirements-lock.txt

# Copy the whole folder inside the Image filesystem
COPY . .

EXPOSE 8000

CMD opentelemetry-instrument gunicorn --bind 0.0.0.0:8000 --timeout=5 --threads=10 "app:create_app()"
