FROM guardrails-api:dev

# Install whatever Hub validators they want
RUN guardrails hub install hub://guardrails/ends_with

# Mount any custom validators to the specified directory
COPY ./custom_validators/* /opt/validators/