# New LiteLLM version has a dependency on madoka which requires g++ to build the wheel
FROM python:3.13

# Set environment variables to avoid writing .pyc files and to unbuffer Python output
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LOGLEVEL="DEBUG"
ENV GUARDRAILS_LOG_LEVEL="DEBUG"
ENV APP_ENVIRONMENT="production"

WORKDIR /app

# Install Git and necessary dependencies
RUN apt-get update && \
    apt-get install -y make git curl gcc jq pipx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:$PATH"

# Copy the entrypoint script
COPY /integration_tests/fastapi-entry.sh /app/fastapi-entry.sh
COPY /integration_tests/integration_tests.env /app/.env
COPY /integration_tests/db.config.py /app/config.py
COPY ../ /app/guardrails-api

# Install guardrails, the guardrails API, and gunicorn
# openai optional. only used for integration testing
RUN pip install "uvicorn[standard]" --no-cache-dir

RUN pip install -U "/app/guardrails-api"

# Install validators; could move this to requirements.txt now if we want
RUN pip install "guardrails-ai-two-words==0.1.0"

# Expose port 8000 for the application
EXPOSE 8000

# Command to start the Gunicorn server with specified settings
CMD ["/bin/bash", "/app/fastapi-entry.sh"]