receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: guardrails

exporters:
  otlp/2:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/2]
    # metrics:
    #   receivers: [otlp]
    #   exporters: [otlp/2]