"""remove unique constraint on guards.name

Revision ID: 680f1675f359
Revises: 66e9df67a7ec
Create Date: 2026-03-23 08:56:27.677378

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "680f1675f359"
down_revision: Union[str, Sequence[str], None] = "66e9df67a7ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("guards_name_unique"), "guards", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("guards_name_unique"),
        "guards",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
