receivers:
  otlp:
    protocols:
      grpc:
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: guardrails

exporters:
  otlp/traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/data-prepper:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:

service:
  telemetry:
    logs:
      level: 'debug'
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/traces, logging]
    metrics:
      receivers: [otlp]
      exporters: [otlp/data-prepper, logging]
    logs:
      receivers: [otlp]
      exporters: [otlp/logs, logging]