receivers:
  otlp:
    protocols:
      grpc:
      # http:

processors:
  batch:

exporters:
  otlp/traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/metrics:
    endpoint: data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true
      insecure_skip_verify: true
  
  # Data sources: metrics
  prometheus:
    endpoint: otel-collector:8889
    namespace: guardrails-api
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  
  # Data sources: traces, metrics, logs
  logging:
    loglevel: ${env:OTEL_PYTHON_LOG_LEVEL}

extensions:
  health_check:

service:
  pipelines:
    traces:
      receivers: 
        - otlp
      processors: 
        - batch
      exporters: 
        - logging
        - otlp/traces
    metrics:
      receivers: 
        - otlp
      processors: 
        - batch
      exporters: 
        - logging
        - otlp/metrics
        - prometheus
    logs:
      receivers: 
        - otlp
      processors: 
        - batch
      exporters: 
        - logging
        - otlp/logs
  telemetry:
    logs:
      level: info